use_frameworks!

platform :ios, '8.0'

target 'GraphVerificationCodeView_Example' do
   pod 'GraphVerificationCodeView', :path => '../'

  target 'GraphVerificationCodeView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
